# Generated by Django 5.0.6 on 2024-05-27 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solucionario', '0002_alter_ocorrencia_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
