# Generated by Django 5.1.2 on 2024-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solucionario', '0003_ocorrencia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='print_ocorrencia',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Imagem'),
        ),
    ]
